name: gg_value
description: GgValue allows managing a value in a dart application. It provides a stream, a flag preventing too many updates, and a custom transform and a comparison function.
version: 0.0.9+2
homepage: https://github.com/gatzsche/gg_value
repository: https://github.com/gatzsche/gg_value

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  fake_async: ^1.1.0
  test: ^1.14.4
