name: gg_value
description: An advanced value representation for dart language.
version: 1.0.0
homepage: https://github.com/gatzsche

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.9.0
  fake_async: ^1.1.0
  test: ^1.14.4
